using System;
using System.Collections.Generic;

namespace TestCaseEditorApp.MVVM.Domains.TestCaseCreation.Models
{
    /// <summary>
    /// LLM-generated test case model with intelligent requirement coverage tracking.
    /// Supports many-to-many relationships where one test case can cover multiple requirements.
    /// </summary>
    public class LLMTestCase
    {
        public string Id { get; set; } = string.Empty;
        public string Title { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public string Preconditions { get; set; } = string.Empty;
        public List<LLMTestStep> Steps { get; set; } = new List<LLMTestStep>();
        public string ExpectedResult { get; set; } = string.Empty;
        public string Postconditions { get; set; } = string.Empty;

        /// <summary>
        /// KEY PROPERTY: List of requirement IDs that this test case covers.
        /// This enables many-to-many relationships via LLM similarity detection.
        /// Examples: ["DECAGON-REQ_RC-5"], ["REQ-1", "REQ-2", "REQ-3"]
        /// </summary>
        public List<string> CoveredRequirementIds { get; set; } = new List<string>();

        public string Priority { get; set; } = "Medium";
        public string TestType { get; set; } = "Functional";
        public int EstimatedDurationMinutes { get; set; }
        public List<string> Tags { get; set; } = new List<string>();
        public DateTime CreatedDate { get; set; } = DateTime.UtcNow;
        public DateTime LastModifiedDate { get; set; } = DateTime.UtcNow;
        public string CreatedBy { get; set; } = "AI-Generated";
        public string Notes { get; set; } = string.Empty;
        public bool IsAutoGenerated { get; set; } = true;

        /// <summary>
        /// LLM confidence score (0-100) indicating how confident the model was
        /// about this test case covering the requirements.
        /// </summary>
        public int GenerationConfidence { get; set; } = 0;
    }
}
