echo "=== Basic Jama OAuth Scope Error Demo ==="
echo ""
echo "Step 1: OAuth Authentication REQUEST"
echo "POST https://yourcompany.jamacloud.com/rest/oauth/token"
echo "Authorization: Basic [base64(client_id:client_secret)]"
echo "Content-Type: application/x-www-form-urlencoded"
echo ""
echo "grant_type=client_credentials"
echo ""
echo "Step 1: OAuth Authentication RESPONSE"
echo "HTTP 200 OK"
echo "{"
echo "  \"access_token\": \"eyJhbGciOiJIUzI1NiJ9...\","
echo "  \"token_type\": \"bearer\","
echo "  \"expires_in\": 3600"
echo "}"
echo ""
echo "Step 2: API Call REQUEST"
echo "GET https://yourcompany.jamacloud.com/rest/v1/projects"
echo "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9..."
echo "Accept: application/json"
echo ""
echo "Step 2: API Call RESPONSE - ERROR"
echo "HTTP 500 Internal Server Error"
echo "{"
echo "  \"meta\": {"
echo "    \"status\": \"error\","
echo "    \"timestamp\": \"2026-01-09T10:30:00Z\""
echo "  },"
echo "  \"error\": {"
echo "    \"message\": \"java.lang.IndexOutOfBounds: Index 0 out of bounds for length 0\","
echo "    \"details\": \"Insufficient scope permissions\""
echo "  }"
echo "}"
echo ""
echo "PROBLEM ANALYSIS:"
echo "  OAuth client scope = 'Token Information' (can only validate tokens)"
echo "  API requires scope = 'read' (can access data endpoints)"
echo ""  
echo "SOLUTION:"
echo "  1. Login to Jama Admin Console"
echo "  2. Go to Admin > OAuth Clients"
echo "  3. Edit your OAuth client"
echo "  4. Change scope from 'Token Information' to 'read'"
echo "  5. Save changes"
echo ""
pause